### ISSUE TITLE
Subtle distance calculation bug

### ISSUE THREAD

**Issue by boydgreenfield** [marbl/Mash#10] opened 2015-10-05 23:45 UTC
In some cases, Mash reports an incorrect numerator (and downstream _distance_ and _p_ values) due to a subtle bug here: https://github.com/marbl/Mash/blob/master/src/mash/CommandDistance.cpp#L417-L435

Specifically, the line:

```cpp
while ( denom < sketchSize && i < hashesSortedRef.size() && j < hashesSortedQry.size() )
```

... causes the distance function to halt when the denominator reaches `sketchSize`, but this can happen prematurely before `hashesSortedRef` is fully iterated through. I _believe_ the simple patch is to fix denominator to `hashesSortedRef.size()` and remove it from the while condition, otherwise the last few elements of the reference/query can be skipped in the comparison.

Here are 2 `.msh` test case files that give `9993/10000` as a result. The number of _minmers_ in the complete union is `9995/10000`:
* [T5.fasta.msh | uploaded via ZenHub](https://files.zenhub.io/561303abac1ef3cd3ae91cae)
* [T6.fasta.msh | uploaded via ZenHub](https://files.zenhub.io/561303abac1ef3cd3ae91cad)

~~PR coming shortly.~~

**Comment by aphillippy** [comment] 2015-10-06 18:54
Nick,
Thanks for digging into the code. I hope you are finding it useful.

Stopping after *s* elements have been processed is the intended behavior. We compute the Jaccard estimate per Broder's suggestion in "On the resemblance and containment of documents". From that paper:

> We store each sketch as a list sorted in increasing order. Then all we have to do is to merge-sort removing duplicates, and count how many duplicates were encountered within the first s outputs.

This effectively computes a size *s* min sketch for the union of the original sets A & B. Thus, the fraction of hashes in this merged sketch that are shared by both A & B is an unbiased estimate of true Jaccard index. The reason to not consider the full sketches: think of the example where the *s* min hashes for A-union-B are all contained in A. In this case, B's hashes should be completely ignored. This is the behavior of the merge operation suggested by Broder.

I'm going to close this issue for now. If you read the original Broder paper and still have an issue with our computation, please let me know. I plan to post the Mash preprint next week, which will also spell this out more clearly and contains the mathematical definition.

Best,
-Adam

**Closed by aphillippy** 2015-10-06 18:54 UTC

**Comment by boydgreenfield** [comment] 2015-10-06 18:56
Hi Adam,

Thanks for the note back – and I suspected there was _some_ chance this was intended, though hard to tell before the preprint is out of course (look forward to reading it!).

Let me look through the Broder paper and if I have any further thoughts I'll post here.

Thanks,
Nick

**Comment by aphillippy** [comment] 2015-10-06 19:10
No problem. Happy you have been poking at the source.

Highly recommend the Broder paper. It's a great one.

**Comment by boydgreenfield** [comment] 2015-10-06 23:39
Hi Adam –

I had a chance to quickly read through the Broder paper, and also give this a bit more thought. For context, we've been working on some similar ideas, but using bitarrays, so my motivation here is in part to achieve concordance between those two schemes.

**First**, please (continue to) disregard my pull request, which does indeed calculate _|A-intersect-B|_, but leaves off the last few elements in B. This simply isn't the Jaccard index (correct numerator, incorrect denominator). 

However, I do wonder if it's better to return the Jaccard index of all of the available sketch content (`9995/10005` for the above two files; _|A-intersect-B|_ over _|A-union-B|_ ), while Mash is returning `9993/10000` due to stopping at _s_. 

Consider the following mock sketches, and the true Jaccard and "Jaccard-stopping-at-_s_" indices:

Sketch A  | Sketch B | Sketch C
------------- | ------------- | ------------- 
2 | 1 | 1
4 | 2 | 3
6 | 3 | 4

  | Jaccard index | Jaccard-stopping-at-_s_ index (current Mash behavior)
------------- | ------------- | ------------- 
_J(A, B)_ | 1/5 | 1/3 
_J(A, C)_ | 1/5 | 0/3
_J(B, C)_ | 2/4 | 2/3


There are two obvious tradeoffs between these schemes and a resulting implementation/design choice:
* **A. Benefits of stopping at _s_**: 
  * (1) Somewhat simpler in that you have a fixed denominator
  * (2) May be better from an implementation perspective for varied size sketches? (haven't given this much thought)
* **B. Downsides**: 
  * (1) Disregards some of the saved sketch data; 
  * (2) Isn't the Jaccard index for the _full_ set of elements in the sketches, making compatibility a bit trickier (e.g., if the _minmers_ were stored in their _k_-mer representation, computing a Mash-equivalent score here would require hashing them with the same algorithm + seed, sorting, and then traversing for _s_ elements)

I think either choice is probably reasonable (my guess is the actual impact of B1 is minimal), but would appreciate your thoughts and comments. And perhaps I've continued to miss something in the Broder paper. :)

– Nick
